# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-18 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190717_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
